/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksCompanyNameRouteImport } from './routes/stacks/$companyName'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksCompanyNameRoute = StacksCompanyNameRouteImport.update({
  id: '/stacks/$companyName',
  path: '/stacks/$companyName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companyName': typeof StacksCompanyNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companyName': typeof StacksCompanyNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companyName': typeof StacksCompanyNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submit' | '/stacks/$companyName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submit' | '/stacks/$companyName'
  id: '__root__' | '/' | '/submit' | '/stacks/$companyName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitRoute: typeof SubmitRoute
  StacksCompanyNameRoute: typeof StacksCompanyNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$companyName': {
      id: '/stacks/$companyName'
      path: '/stacks/$companyName'
      fullPath: '/stacks/$companyName'
      preLoaderRoute: typeof StacksCompanyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitRoute: SubmitRoute,
  StacksCompanyNameRoute: StacksCompanyNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
