/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksCompanySlugRouteImport } from './routes/stacks/$companySlug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksCompanySlugRoute = StacksCompanySlugRouteImport.update({
  id: '/stacks/$companySlug',
  path: '/stacks/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companySlug': typeof StacksCompanySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companySlug': typeof StacksCompanySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/stacks/$companySlug': typeof StacksCompanySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submit' | '/stacks/$companySlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submit' | '/stacks/$companySlug'
  id: '__root__' | '/' | '/submit' | '/stacks/$companySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitRoute: typeof SubmitRoute
  StacksCompanySlugRoute: typeof StacksCompanySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$companySlug': {
      id: '/stacks/$companySlug'
      path: '/stacks/$companySlug'
      fullPath: '/stacks/$companySlug'
      preLoaderRoute: typeof StacksCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitRoute: SubmitRoute,
  StacksCompanySlugRoute: StacksCompanySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
